# Generated by Django 4.2.3 on 2023-07-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_defaultdate_wordcloud_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='wfootball', max_length=20),
            preserve_default=False,
        ),
    ]
