# Generated by Django 4.2.3 on 2023-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='category',
            field=models.CharField(default='wfootball', max_length=20),
            preserve_default=False,
        ),
    ]
