# Generated by Django 4.2.3 on 2023-07-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wordcloud_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdate',
            name='crawl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultdate',
            name='sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultdate',
            name='date',
            field=models.DateField(default='2023-07-14'),
        ),
    ]
